// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TechTickles.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FeatureSubscriptionPlan", b =>
                {
                    b.Property<int>("FeatureFeatureId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionPlanPlanId")
                        .HasColumnType("int");

                    b.HasKey("FeatureFeatureId", "SubscriptionPlanPlanId");

                    b.HasIndex("SubscriptionPlanPlanId");

                    b.ToTable("SubscriptionPlanFeatures", (string)null);

                    b.HasData(
                        new
                        {
                            FeatureFeatureId = 1,
                            SubscriptionPlanPlanId = 1
                        },
                        new
                        {
                            FeatureFeatureId = 8,
                            SubscriptionPlanPlanId = 2
                        },
                        new
                        {
                            FeatureFeatureId = 7,
                            SubscriptionPlanPlanId = 2
                        },
                        new
                        {
                            FeatureFeatureId = 9,
                            SubscriptionPlanPlanId = 2
                        },
                        new
                        {
                            FeatureFeatureId = 7,
                            SubscriptionPlanPlanId = 3
                        },
                        new
                        {
                            FeatureFeatureId = 8,
                            SubscriptionPlanPlanId = 3
                        },
                        new
                        {
                            FeatureFeatureId = 3,
                            SubscriptionPlanPlanId = 3
                        },
                        new
                        {
                            FeatureFeatureId = 6,
                            SubscriptionPlanPlanId = 3
                        },
                        new
                        {
                            FeatureFeatureId = 9,
                            SubscriptionPlanPlanId = 3
                        },
                        new
                        {
                            FeatureFeatureId = 10,
                            SubscriptionPlanPlanId = 3
                        },
                        new
                        {
                            FeatureFeatureId = 7,
                            SubscriptionPlanPlanId = 4
                        },
                        new
                        {
                            FeatureFeatureId = 8,
                            SubscriptionPlanPlanId = 4
                        },
                        new
                        {
                            FeatureFeatureId = 3,
                            SubscriptionPlanPlanId = 4
                        },
                        new
                        {
                            FeatureFeatureId = 6,
                            SubscriptionPlanPlanId = 4
                        },
                        new
                        {
                            FeatureFeatureId = 9,
                            SubscriptionPlanPlanId = 4
                        },
                        new
                        {
                            FeatureFeatureId = 10,
                            SubscriptionPlanPlanId = 4
                        },
                        new
                        {
                            FeatureFeatureId = 5,
                            SubscriptionPlanPlanId = 4
                        },
                        new
                        {
                            FeatureFeatureId = 4,
                            SubscriptionPlanPlanId = 4
                        },
                        new
                        {
                            FeatureFeatureId = 2,
                            SubscriptionPlanPlanId = 4
                        });
                });

            modelBuilder.Entity("TechTickles.Models.Cart", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("PlanId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("TechTickles.Models.CreditCard", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CVV")
                        .HasColumnType("int");

                    b.Property<long>("CardNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Expiration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AccountId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("TechTickles.Models.Customer", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TechTickles.Models.CustomerSubscription", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AccountId");

                    b.HasIndex("PlanId");

                    b.ToTable("CustomerSubscriptions");
                });

            modelBuilder.Entity("TechTickles.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripton")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FeatureId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            Descripton = "No Features",
                            Name = "No Features"
                        },
                        new
                        {
                            FeatureId = 2,
                            Descripton = "Detects malware while you are on the web and as soon as a malicious site attempts to invade our software will remove it immediately",
                            Name = "Real-Time Malware Protection"
                        },
                        new
                        {
                            FeatureId = 3,
                            Descripton = "High-Speed secure internet connection that blocks your IP address and prevents network based attacks",
                            Name = "Virtual Private Network(VPN)"
                        },
                        new
                        {
                            FeatureId = 4,
                            Descripton = "Real-Time Virus Detection while you are browsing and downloading from the web, then our software will remove this without you knowing",
                            Name = "Real-Time Antivirus Protection"
                        },
                        new
                        {
                            FeatureId = 5,
                            Descripton = "Clean your digital footprint from spam websites and scams and preventing your digital footprint to leave a trail on all the sits you visit",
                            Name = "Data Scrubber"
                        },
                        new
                        {
                            FeatureId = 6,
                            Descripton = "Tracks where your information is being used and detects if your personal information has been leaked such as payment information, and key identity informaton",
                            Name = "Identity Theft Protection"
                        },
                        new
                        {
                            FeatureId = 7,
                            Descripton = "Prevent pop-up ads from injecting malware into your system. This software detects websites trying to give pop-up ads and prevents it from being shown",
                            Name = "Ad Blocker"
                        },
                        new
                        {
                            FeatureId = 8,
                            Descripton = "Scan through your computer's internal drive and history for potential malware rooted inside",
                            Name = "Limited Malware and Virus Scan"
                        },
                        new
                        {
                            FeatureId = 9,
                            Descripton = "Securely store your passwords and generate strong passwords for you to use. Protected by our own database your passwords will be protected from being leaked",
                            Name = "Password Manager"
                        },
                        new
                        {
                            FeatureId = 10,
                            Descripton = "Permanently delete files from your computer and prevent them from being recovered by hackers. Important for confidential files related to your personal data",
                            Name = "Secure File Shredder"
                        });
                });

            modelBuilder.Entity("TechTickles.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReviewId");

                    b.HasIndex("AccountId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TechTickles.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("PlanId");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            Description = "You are not subscribed to any plan!",
                            Name = "None",
                            Price = 0.0
                        },
                        new
                        {
                            PlanId = 2,
                            Description = "This is a basic plan that includes featues that are essential to protect your information on the web like: Ad Blocker, Limited Malware and Virus Scans, and an efficient Password Manager",
                            Name = "Tickles Basic",
                            Price = 50.0
                        },
                        new
                        {
                            PlanId = 3,
                            Description = "Middle tier plan providing more security measures for users that are more active on the web. This plan includes all the features from the Basic plan and adds: Virtual Private Network(VPN), Identity Theft Protection, and a Secure File Shredder",
                            Name = "Tickles Plus",
                            Price = 89.0
                        },
                        new
                        {
                            PlanId = 4,
                            Description = "Top of the line plan with every security measure taken to protect your information on the web. This plan includes all of the features of the other plans and adds : Data Scrubber, Real-Time Malware and Virus Protection",
                            Name = "Tickles Ultimate",
                            Price = 101.0
                        });
                });

            modelBuilder.Entity("FeatureSubscriptionPlan", b =>
                {
                    b.HasOne("TechTickles.Models.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeatureFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechTickles.Models.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechTickles.Models.Cart", b =>
                {
                    b.HasOne("TechTickles.Models.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("TechTickles.Models.Cart", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechTickles.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Carts")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("TechTickles.Models.CreditCard", b =>
                {
                    b.HasOne("TechTickles.Models.Customer", "CardOwner")
                        .WithOne("cardInfo")
                        .HasForeignKey("TechTickles.Models.CreditCard", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardOwner");
                });

            modelBuilder.Entity("TechTickles.Models.CustomerSubscription", b =>
                {
                    b.HasOne("TechTickles.Models.Customer", "Customer")
                        .WithOne("Subscription")
                        .HasForeignKey("TechTickles.Models.CustomerSubscription", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechTickles.Models.SubscriptionPlan", "Plan")
                        .WithMany("CustomerSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TechTickles.Models.Review", b =>
                {
                    b.HasOne("TechTickles.Models.Customer", "Customer")
                        .WithMany("reviews")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TechTickles.Models.Customer", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Subscription")
                        .IsRequired();

                    b.Navigation("cardInfo")
                        .IsRequired();

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("TechTickles.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("CustomerSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
